default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  

development:
  <<: *default
  database: rev_app_dev
  username: rails
  password: rails@123
test:
  <<: *default
  database: rev_app_test
  username: rails
  password: rails@123
production:
  <<: *default
  database: rev_app_prd
  username:
  password: